const express = require("express");
const mongoose = require("mongoose");
const bodyParser = require("body-parser")
// const fs = require("fs")

const cloudinary = require("cloudinary").v2
cloudinary.config({ 
    cloud_name: 'deaz1bojg', 
    api_key: '645723722777177', 
    api_secret: 'XRGgePHQU2pAdluBm1nDxjCQ3_c' 
});


const index = require("./Routes/index")

const app = express()
const mongoURI = "mongodb://localhost/E-dealers"

// app.use(methodOverride('_method'));

app.use(bodyParser.json({limit: '50mb'}));
app.use(bodyParser.urlencoded({limit: '50mb', extended: true}));


// cloudinary.uploader.upload('IMG-3144.JPG', { tags: 'basic_sample' }, function (err, image) {
//     console.log();
//     console.log("** File Upload"); 
//     if (err) { console.log("error",err); }
//     console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
//     // console.log("* " + image.public_id);
//     // console.log("* " + image.url);
//     // waitForAllUploads("pizza", err, image);
//   });

//   // Stream upload
// var upload_stream = cloudinary.uploader.upload_stream({ tags: 'basic_sample' }, function (err, image) {
//     console.log();
//     console.log("** Stream Upload");
//     if (err) { console.warn(err); }
//     console.log("* Same image, uploaded via stream");
//     // console.log("* " + image.public_id);
//     // console.log("* " + image.url);
//     // waitForAllUploads("pizza3", err, image);
//   });
//   var file_reader = fs.createReadStream('1.png').pipe(upload_stream)



mongoose.connect(mongoURI,{ useNewUrlParser: true })
.then( () => console.log("successfully connected to mongoDB") )
.catch( (err) => console.log("err",err) )


// app.post('/upload',upload.single("fileName"), (req, res) => {
//     // res.sendFile(path.join(__dirname + '/ShoppingCart-React/public/index.html'));
//     console.log("fileName",req.body.fileName)
//     // res.json({ file: req.file });
//     // res.redirect('/');
//   });


app.get("/", (req,res) =>{
    res.send("working server");

})  
// app.get("/getImages",(req,res)=> {
//   cloudinary.api.resources((error,result) => {
//     res.send( result.resources)
//   })
// })

app.use("/",index)

const port = process.env.PORT || 5000

app.listen(port, () => console.log(`server running on port ${port}`))